version: '3.8'

services:
  backup:
    depends_on:
      - httpd
    image: zeeemughal/docker-volume-backup
    environment:
      - TZ=Asia/Karachi
      - DOCKER_CONTAINER_STOP=magical_ganguly
      - RESTIC_REPOSITORY=rclone:gdrive:/backup
      # Set the backup cron schedule
      - BACKUP_CRON=* * * * *
      # Set the forget cron schedule
      - PRUNE_CRON=* * * * *
      - RESTIC_FORGET_ARGS=--prune --keep-last 2
      # Set Run on startup to true/false
      - RUN_ON_STARTUP=true
      - CHECK_CRON=51 20 * * *
      - RESTIC_CHECK_ARGS=--read-data
      - DOCKER_STOP_CONTAINERS=httpd-server
      - RESTIC_PASSWORD=your_password
    volumes:
      # This is the container volume to backup 
      - volume_name:/data/backup
      # Mount docker socket to allow container management
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the rclone config directory to the container
      - ~/.config/rclone:/root/.config/rclone

    # Uncomment the following lines to restore the backup on startup and set Run on startup to false

    # entrypoint:
    #   - "/bin/sh"
    #   - "-c"
    #   - "restic restore latest --target /"

  httpd:
    image: httpd:latest
    container_name: httpd-server
    ports:
      - "80:80"